import email from "assets/svg/email.svg";
import logo from "assets/svg/logo.svg";
import phone from "assets/svg/phone.svg";

import {
  faCircleDot,
  faSquarePlus,
  faSquareMinus,
  faCartShopping,
  faPencil,
  faPenToSquare,
  faCircleXmark,
  faBookmark,
  faStar,
  faBars,
  faFileLines,
  faClock,
  faCartPlus,
  faMagnifyingGlass,
  faCommentDots,
  faTimes,
  faAngleLeft,
  faAngleRight,
  faQuoteLeft,
  faPlay,
  faCircleExclamation,
  faCircleQuestion,
  faCircleCheck,
  faCircleUser,
  faList,
  faIndianRupeeSign,
  faFilter,
  faBarsFilter,
  faBarcode,
  faBarChart,
  faPaperclip,
} from "@fortawesome/free-solid-svg-icons";

import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export const svgIcons = {
  email,
  logo,
  phone,
};
export const icons = {
  FontAwesomeIcon,
  faCircleDot,
  faSquarePlus,
  faSquareMinus,
  faCartShopping,
  faPencil,
  faPenToSquare,
  faCircleXmark,
  faBookmark,
  faStar,
  faBars,
  faFileLines,
  faClock,
  faCartPlus,
  faMagnifyingGlass,
  faCommentDots,
  faTimes,
  faAngleLeft,
  faAngleRight,
  faQuoteLeft,
  faPlay,
  faCircleExclamation,
  faCircleQuestion,
  faCircleCheck,
  faCircleUser,
  faList,
  faIndianRupeeSign,
  faFilter,
  faBarcode,
  faBarsFilter,
  faBarChart,
  faPaperclip,
};
